#!/usr/bin/env bash
# Nginx running on Port 80

sudo sed -i -e "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sudo sed -i -e "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/g" /etc/nginx/sites-enabled/default
service nginx restart
